"""initial schema

Revision ID: 147b79f0b22f
Revises: 
Create Date: 2026-04-30 17:05:02.022821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147b79f0b22f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称，唯一'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='标签表，存储所有可用的标签'
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Ticket 标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='Ticket 详细描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：open-未完成, closed-已完成'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.CheckConstraint("status IN ('open', 'closed')", name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ticket 主表，存储所有工单信息'
    )
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='关联的 Ticket ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='关联的 Tag ID'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id'),
    comment='Ticket 和 Tag 的多对多关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_tags')
    op.drop_table('tickets')
    op.drop_table('tags')
    # ### end Alembic commands ###
